name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - dev/*

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 2.8.0
          prettier_plugins: "prettier-plugin-svelte"
          prettier_options: ${{ vars.PRETTIER_OPTIONS }}
